### ISSUE TITLE
"Exit" throws an error when called within worker

### ISSUE THREAD

**Issue by donkalar** [gnufied/backgroundrb#4]
Calls to exit() seem to be broken in the master branch, which results in zombie workers until backgroundrb is cycled.

**Comment by donkalar** [comment]
I added a backtrace print to the error handler, and the call stack is as follows:

/Users/don/Code/Rails/pubbrain/lib/workers/run_search_worker.rb:117:in 'exit'
/Users/don/Code/Rails/pubbrain/lib/workers/run_search_worker.rb:117:in 'create'
/Users/don/Code/Rails/pubbrain/vendor/plugins/backgroundrb/server/lib/meta_worker.rb:320:in 'send'
/Users/don/Code/Rails/pubbrain/vendor/plugins/backgroundrb/server/lib/meta_worker.rb:320:in 'invoke_user_method'
/Users/don/Code/Rails/pubbrain/vendor/plugins/backgroundrb/server/lib/meta_worker.rb:127:in 'worker_init'
/Library/Ruby/Gems/1.8/gems/packet-0.1.15/bin/../lib/packet/packet_worker.rb:19:in 'start_worker'
/Library/Ruby/Gems/1.8/gems/packet-0.1.15/bin/packet_worker_runner:33:in 'load_worker'
/Library/Ruby/Gems/1.8/gems/packet-0.1.15/bin/packet_worker_runner:26:in 'initialize'
/Library/Ruby/Gems/1.8/gems/packet-0.1.15/bin/packet_worker_runner:47:in 'new'
/Library/Ruby/Gems/1.8/gems/packet-0.1.15/bin/packet_worker_runner:47
/usr/bin/packet_worker_runner:19:in 'load'
/usr/bin/packet_worker_runner:19

**Comment by fonsecajavier** [comment]
Any updates on this issue?
